# This is a basic workflow to help you get started with Actions
name: Update Release notes

# Controls when the workflow will run
on:
 release:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: NPM build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - name: Update release for ${{ github.event.client_payload.ReleaseBranchName }}
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            var json = JSON.parse(fs.readFileSync('./releasenotes.json').toString());
            var html = "";
              for(const coin in json){
                  html += "<h1>"+coin+"</h1>";
                  html += json[coin].wall+"<br>";
                  html += json[coin].scan+"<br>";
              }
              const response = await github.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: "${{ github.event.client_payload.ReleaseBranchName }}"
              });
              github.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: response.data.id,
                body: html
              });
